default_agent: agentcore_starter_strands
agents:
  agentcore_starter_strands:
    name: agentcore_starter_strands
    entrypoint: /Users/sohampatil/Documents/Projects/NexAI - AWS AI Hackathon/Code/Demo_Agentcore_Bedrock/agentcore_starter_strands.py
    platform: linux/arm64
    container_runtime: none
    source_path: /Users/sohampatil/Documents/Projects/NexAI - AWS AI Hackathon/Code/Demo_Agentcore_Bedrock
    aws:
      execution_role: arn:aws:iam::897722666599:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-9c0804ec0c
      execution_role_auto_create: false
      account: '897722666599'
      region: us-east-1
      ecr_repository: 897722666599.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-agentcore_starter_strands
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: agentcore_starter_strands-0vbB2fHbBv
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:897722666599:runtime/agentcore_starter_strands-0vbB2fHbBv
      agent_session_id: 4444227b-a7e4-4b92-8dc6-672dc583f345
    codebuild:
      project_name: bedrock-agentcore-agentcore_starter_strands-builder
      execution_role: arn:aws:iam::897722666599:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-9c0804ec0c
      source_bucket: bedrock-agentcore-codebuild-sources-897722666599-us-east-1
    memory:
      mode: STM_AND_LTM
      memory_id: agentcore_starter_strands_mem-R9geFTH0VY
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:897722666599:memory/agentcore_starter_strands_mem-R9geFTH0VY
      memory_name: agentcore_starter_strands_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
